In [1]:
sp500_tickers = [
    'MMM', 'AOS', 'ABT', 'ABBV', 'ACN', 'ADBE', 'AMD', 'AES', 'AFL', 'A', 
    'APD', 'AKAM', 'ALK', 'ALB', 'ARE', 'ALGN', 'ALLE', 'LNT', 'ALL', 'GOOGL', 
    'GOOG', 'MO', 'AMZN', 'AMCR', 'AEE', 'AAL', 'AEP', 'AXP', 'AIG', 'AMT', 
    'AWK', 'AMP', 'ABC', 'AME', 'AMGN', 'APH', 'ADI', 'ANSS', 'AON', 'APA', 
    'AAPL', 'AMAT', 'APTV', 'ACGL', 'ANET', 'AJG', 'AIZ', 'T', 'ATO', 'ADSK', 
    'AZO', 'AVB', 'AVY', 'BKR', 'BALL', 'BAC', 'BBWI', 'BAX', 'BDX', 'WRB', 
    'BRK.B', 'BBY', 'BIO', 'TECH', 'BIIB', 'BLK', 'BK', 'BA', 'BKNG', 'BWA', 
    'BXP', 'BSX', 'BMY', 'AVGO', 'BR', 'BRO', 'BF.B', 'CHRW', 'CDNS', 'CZR', 
    'CPB', 'COF', 'CAH', 'KMX', 'CCL', 'CARR', 'CTLT', 'CAT', 'CBOE', 'CBRE', 
    'CDW', 'CE', 'CNC', 'CNP', 'CDAY', 'CF', 'CRL', 'SCHW', 'CHTR', 'CVX', 
    'CMG', 'CB', 'CHD', 'CI', 'CINF', 'CTAS', 'CSCO', 'C', 'CFG', 'CLX', 
    'CME', 'CMS', 'KO', 'CTSH', 'CL', 'CMCSA', 'CMA', 'CAG', 'COP', 'ED', 
    'STZ', 'CPRT', 'GLW', 'CTVA', 'COST', 'CTRA', 'CCI', 'CSX', 'CMI', 'CVS', 
    'DHI', 'DHR', 'DRI', 'DVA', 'DE', 'DAL', 'XRAY', 'DVN', 'DXCM', 'FANG', 
    'DLR', 'DFS', 'DIS', 'DG', 'DLTR', 'D', 'DPZ', 'DOV', 'DOW', 'DTE', 
    'DUK', 'DD', 'DXC', 'EMN', 'ETN', 'EBAY', 'ECL', 'EIX', 'EW', 'EA', 
    'ELV', 'LLY', 'EMR', 'ENPH', 'ETR', 'EOG', 'EPAM', 'EQT', 'EFX', 'EQIX', 
    'EQR', 'ESS', 'EL', 'ETSY', 'EG', 'EVRG', 'ES', 'EXC', 'EXPE', 'EXPD', 
    'EXR', 'XOM', 'FFIV', 'FDS', 'FAST', 'FRT', 'FDX', 'FITB', 'FSLR', 'FE', 
    'FIS', 'FISV', 'FLT', 'FMC', 'F', 'FTNT', 'FTV', 'FOXA', 'FOX', 'BEN', 
    'FCX', 'GRMN', 'IT', 'GE', 'GEN', 'GNRC', 'GD', 'GIS', 'GM', 'GPC', 
    'GILD', 'GL', 'GPN', 'GS', 'HAL', 'HIG', 'HAS', 'HCA', 'PEAK', 'HSIC', 
    'HES', 'HPE', 'HLT', 'HOLX', 'HD', 'HON', 'HRL', 'HST', 'HWM', 'HPQ', 
    'HUM', 'HBAN', 'HII', 'IBM', 'IEX', 'IDXX', 'ITW', 'ILMN', 'INCY', 'IR', 
    'INTC', 'ICE', 'IP', 'IPG', 'IFF', 'INTU', 'ISRG', 'IVZ', 'INVH', 'IQV', 
    'IRM', 'JBHT', 'JKHY', 'J', 'JNJ', 'JCI', 'JPM', 'JNPR', 'K', 'KDP', 
    'KEY', 'KEYS', 'KMB', 'KIM', 'KMI', 'KLAC', 'KHC', 'KR', 'LHX', 'LH', 
    'LRCX', 'LW', 'LVS', 'LDOS', 'LEN', 'LNC', 'LIN', 'LYV', 'LKQ', 'LMT', 
    'L', 'LOW', 'LUMN', 'LYB', 'MTB', 'MRO', 'MPC', 'MKTX', 'MAR', 'MMC', 
    'MLM', 'MAS', 'MA', 'MTCH', 'MKC', 'MCD', 'MCK', 'MDT', 'MRK', 'META', 
    'MET', 'MTD', 'MGM', 'MCHP', 'MU', 'MSFT', 'MAA', 'MRNA', 'MHK', 'MOH', 
    'TAP', 'MDLZ', 'MPWR', 'MNST', 'MCO', 'MS', 'MOS', 'MSI', 'MSCI', 'NDAQ', 
    'NTAP', 'NFLX', 'NWL', 'NEM', 'NWSA', 'NWS', 'NEE', 'NKE', 'NI', 'NDSN', 
    'NSC', 'NTRS', 'NOC', 'NCLH', 'NRG', 'NUE', 'NVDA', 'NVR', 'NXPI', 'ORLY', 
    'OXY', 'ODFL', 'OMC', 'ON', 'OKE', 'ORCL', 'OGN', 'OTIS', 'PCAR', 'PKG', 
    'PANW', 'PARA', 'PH', 'PAYX', 'PAYC', 'PYPL', 'PNR', 'PEP', 'PFE', 'PCG', 
    'PM', 'PSX', 'PNW', 'PXD', 'PNC', 'POOL', 'PPG', 'PPL', 'PFG', 'PG', 
    'PGR', 'PLD', 'PRU', 'PEG', 'PTC', 'PSA', 'PHM', 'QRVO', 'PWR', 'QCOM', 
    'DGX', 'RL', 'RJF', 'RTX', 'O', 'REG', 'REGN', 'RF', 'RSG', 'RMD', 'RVTY', 
    'RHI', 'ROK', 'ROL', 'ROP', 'ROST', 'RCL', 'SPGI', 'CRM', 'SBAC', 'SLB', 
    'STX', 'SEE', 'SRE', 'NOW', 'SHW', 'SPG', 'SWKS', 'SJM', 'SNA', 'SEDG', 
    'SO', 'LUV', 'SWK', 'SBUX', 'STT', 'STLD', 'STE', 'SYK', 'SYF', 'SNPS', 
    'SYY', 'TMUS', 'TROW', 'TTWO', 'TPR', 'TRGP', 'TGT', 'TEL', 'TDY', 'TFX', 
    'TER', 'TSLA', 'TXN', 'TXT', 'TMO', 'TJX', 'TSCO', 'TT', 'TDG', 'TRV', 
    'TRMB', 'TFC', 'TYL', 'TSN', 'USB', 'UDR', 'ULTA', 'UNP', 'UAL', 'UPS', 
    'URI', 'UNH', 'UHS', 'VLO', 'VTR', 'VRSN', 'VRSK', 'VZ', 'VRTX', 'VFC', 
    'VTRS', 'VICI', 'V', 'VMC', 'WAB', 'WBA', 'WMT', 'WBD', 'WM', 'WAT', 
    'WEC', 'WFC', 'WELL', 'WST', 'WDC', 'WRK', 'WY', 'WHR', 'WMB', 'WTW', 
    'GWW', 'WYNN', 'XEL', 'XYL', 'YUM', 'ZBRA', 'ZBH', 'ZION', 'ZTS'
]

In [4]:
import yfinance as yf
import pandas as pd
from datetime import datetime

def download_and_transform_data(tickers, period="10y"):
    """Загружает месячные данные и преобразует в нужный формат"""
    try:
        data = yf.download(
            tickers=tickers,
            period=period,
            interval="1mo",  # Месячные данные
            group_by='ticker',
            progress=True,
            threads=True
        )

        # Собираем данные в список DataFrame'ов
        frames = []
        for ticker in tickers:
            if ticker in data:
                # Создаем копию данных для текущего тикера
                df = data[ticker].copy()
                # Сбрасываем индекс, чтобы 'Date' стал обычным столбцом
                df = df.reset_index()
                # Добавляем столбец с тикером
                df['symbol'] = ticker
                frames.append(df)

        if not frames:
            return pd.DataFrame()

        # Объединяем все DataFrame'ы
        combined = pd.concat(frames, ignore_index=True)

        # Сортируем по тикеру и дате
        combined = combined.sort_values(['symbol', 'Date'])

        # Создаем целевую переменную (месячная доходность)
        # Используем shift(-1) для следующего месяца
        combined['next_month_close'] = combined.groupby('symbol')['Close'].shift(-1)
        combined['month_return'] = (combined['next_month_close'] / combined['Close']) - 1

        # Удаляем последний месяц для каждого тикера, так как для него нет будущей цены
        combined = combined.dropna(subset=['month_return'])

        return combined

    except Exception as e:
        print(f"Ошибка при загрузке и преобразовании данных: {e}")
        return pd.DataFrame()

def save_to_csv(data, filename_prefix="sp500_ml_data"):
    """Сохраняет данные в CSV файл"""
    if data is None or data.empty:
        print("Нет данных для сохранения")
        return

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"data/{filename_prefix}_{timestamp}.csv"
    data.to_csv(filename, index=False)
    print(f"Данные сохранены в файл: {filename}")

def main(top_tickers=sp500_tickers):
    print("Получаем топ 20 акций S&P 500 по капитализации...")
    if top_tickers == []:
        top_tickers = get_top_sp500_tickers(top_n=20)

    if not top_tickers:
        print("Не удалось получить список акций. Завершение работы.")
        return

    print(f"Топ 20 акций по капитализации: {', '.join(top_tickers)}")

    print("Загружаем и преобразуем исторические данные...")
    stock_data = download_and_transform_data(top_tickers, period="10y")

    if not stock_data.empty:
        print("\nУспешно загружены и преобразованы данные:")
        print(stock_data.head())

        save_to_csv(stock_data, "sp500_ml_monthly")
    else:
        print("Не удалось загрузить данные или данные пусты.")

In [5]:
main()

Получаем топ 20 акций S&P 500 по капитализации...
Топ 20 акций по капитализации: MMM, AOS, ABT, ABBV, ACN, ADBE, AMD, AES, AFL, A, APD, AKAM, ALK, ALB, ARE, ALGN, ALLE, LNT, ALL, GOOGL, GOOG, MO, AMZN, AMCR, AEE, AAL, AEP, AXP, AIG, AMT, AWK, AMP, ABC, AME, AMGN, APH, ADI, ANSS, AON, APA, AAPL, AMAT, APTV, ACGL, ANET, AJG, AIZ, T, ATO, ADSK, AZO, AVB, AVY, BKR, BALL, BAC, BBWI, BAX, BDX, WRB, BRK.B, BBY, BIO, TECH, BIIB, BLK, BK, BA, BKNG, BWA, BXP, BSX, BMY, AVGO, BR, BRO, BF.B, CHRW, CDNS, CZR, CPB, COF, CAH, KMX, CCL, CARR, CTLT, CAT, CBOE, CBRE, CDW, CE, CNC, CNP, CDAY, CF, CRL, SCHW, CHTR, CVX, CMG, CB, CHD, CI, CINF, CTAS, CSCO, C, CFG, CLX, CME, CMS, KO, CTSH, CL, CMCSA, CMA, CAG, COP, ED, STZ, CPRT, GLW, CTVA, COST, CTRA, CCI, CSX, CMI, CVS, DHI, DHR, DRI, DVA, DE, DAL, XRAY, DVN, DXCM, FANG, DLR, DFS, DIS, DG, DLTR, D, DPZ, DOV, DOW, DTE, DUK, DD, DXC, EMN, ETN, EBAY, ECL, EIX, EW, EA, ELV, LLY, EMR, ENPH, ETR, EOG, EPAM, EQT, EFX, EQIX, EQR, ESS, EL, ETSY, EG, EVRG, ES, EXC, EXPE, EXPD, EXR, XOM, FFIV, FDS, FAST, FRT, FDX, FITB, FSLR, FE, FIS, FISV, FLT, FMC, F, FTNT, FTV, FOXA, FOX, BEN, FCX, GRMN, IT, GE, GEN, GNRC, GD, GIS, GM, GPC, GILD, GL, GPN, GS, HAL, HIG, HAS, HCA, PEAK, HSIC, HES, HPE, HLT, HOLX, HD, HON, HRL, HST, HWM, HPQ, HUM, HBAN, HII, IBM, IEX, IDXX, ITW, ILMN, INCY, IR, INTC, ICE, IP, IPG, IFF, INTU, ISRG, IVZ, INVH, IQV, IRM, JBHT, JKHY, J, JNJ, JCI, JPM, JNPR, K, KDP, KEY, KEYS, KMB, KIM, KMI, KLAC, KHC, KR, LHX, LH, LRCX, LW, LVS, LDOS, LEN, LNC, LIN, LYV, LKQ, LMT, L, LOW, LUMN, LYB, MTB, MRO, MPC, MKTX, MAR, MMC, MLM, MAS, MA, MTCH, MKC, MCD, MCK, MDT, MRK, META, MET, MTD, MGM, MCHP, MU, MSFT, MAA, MRNA, MHK, MOH, TAP, MDLZ, MPWR, MNST, MCO, MS, MOS, MSI, MSCI, NDAQ, NTAP, NFLX, NWL, NEM, NWSA, NWS, NEE, NKE, NI, NDSN, NSC, NTRS, NOC, NCLH, NRG, NUE, NVDA, NVR, NXPI, ORLY, OXY, ODFL, OMC, ON, OKE, ORCL, OGN, OTIS, PCAR, PKG, PANW, PARA, PH, PAYX, PAYC, PYPL, PNR, PEP, PFE, PCG, PM, PSX, PNW, PXD, PNC, POOL, PPG, PPL, PFG, PG, PGR, PLD, PRU, PEG, PTC, PSA, PHM, QRVO, PWR, QCOM, DGX, RL, RJF, RTX, O, REG, REGN, RF, RSG, RMD, RVTY, RHI, ROK, ROL, ROP, ROST, RCL, SPGI, CRM, SBAC, SLB, STX, SEE, SRE, NOW, SHW, SPG, SWKS, SJM, SNA, SEDG, SO, LUV, SWK, SBUX, STT, STLD, STE, SYK, SYF, SNPS, SYY, TMUS, TROW, TTWO, TPR, TRGP, TGT, TEL, TDY, TFX, TER, TSLA, TXN, TXT, TMO, TJX, TSCO, TT, TDG, TRV, TRMB, TFC, TYL, TSN, USB, UDR, ULTA, UNP, UAL, UPS, URI, UNH, UHS, VLO, VTR, VRSN, VRSK, VZ, VRTX, VFC, VTRS, VICI, V, VMC, WAB, WBA, WMT, WBD, WM, WAT, WEC, WFC, WELL, WST, WDC, WRK, WY, WHR, WMB, WTW, GWW, WYNN, XEL, XYL, YUM, ZBRA, ZBH, ZION, ZTS
Загружаем и преобразуем исторические данные...

[*********************100%***********************]  490 of 490 completed

11 Failed downloads:
['MRO', 'BRK.B', 'WRK', 'CDAY', 'CTLT', 'FLT', 'PXD', 'ABC', 'FISV', 'PEAK']: YFPricesMissingError('possibly delisted; no price data found  (period=10y) (Yahoo error = "No data found, symbol may be delisted")')
['BF.B']: YFPricesMissingError('possibly delisted; no price data found  (period=10y)')

Успешно загружены и преобразованы данные:
Price       Date       Open       High        Low      Close      Volume  \
1080  2015-06-01  38.167115  38.167115  35.449446  35.541573  58978100.0
1081  2015-07-01  35.916834  37.994820  35.658242  37.819347  54238300.0
1082  2015-08-01  37.791632  38.188758  31.003547  33.534073  56307300.0
1083  2015-09-01  32.601296  34.162097  30.698787  31.705456  47113000.0
1084  2015-10-01  31.788222  35.289371  30.676745  34.974453  52993300.0

Price symbol  Adj Close  next_month_close  month_return
1080       A        NaN         37.819347      0.064088
1081       A        NaN         33.534073     -0.113309
1082       A        NaN         31.705456     -0.054530
1083       A        NaN         34.974453      0.103105
1084       A        NaN         38.734951      0.107521
Данные сохранены в файл: data/sp500_ml_monthly_20250516_120505.csv

In [12]:
df = pd.read_csv("data/sp500_ml_monthly_20250516_120505.csv")
df.drop('Adj Close', axis=1, inplace=True)

In [13]:
import pandas as pd
import pandas_ta as ta

# Предположим, df содержит ежемесячные данные с колонками 'Date', 'Open', 'High', 'Low', 'Close', 'Volume'

# --- Тренд ---
df['ema_3'] = ta.ema(df['Close'], length=3)
df['ema_6'] = ta.ema(df['Close'], length=6)
df['ema_12'] = ta.ema(df['Close'], length=12)
df['ema_12'] = ta.ema(df['Close'], length=18)
df['ema_24'] = ta.ema(df['Close'], length=24)

# --- Моментум ---
df['rsi_3'] = ta.rsi(df['Close'], length=3)
df['rsi_7'] = ta.rsi(df['Close'], length=7)
df['rsi_14'] = ta.rsi(df['Close'], length=14)

# --- MACD с разными параметрами ---
df['macd_fast'] = ta.macd(df['Close'], fast=8, slow=15, signal=5)['MACD_8_15_5']
df['macd_slow'] = ta.macd(df['Close'], fast=12, slow=26, signal=9)['MACD_12_26_9']

# --- Волатильность ---
df['atr_7'] = ta.atr(df['High'], df['Low'], df['Close'], length=7)
df['atr_14'] = ta.atr(df['High'], df['Low'], df['Close'], length=14)

# --- Баланс объёма ---
if 'Volume' in df.columns:
    df['obv_short'] = ta.obv(df['Close'], df['Volume'])
    df['cmf_short'] = ta.cmf(df['High'], df['Low'], df['Close'], df['Volume'], length=7)

# Целевая переменная
df['target_return'] = df['Close'].shift(-1) / df['Close'] - 1

df

,Date,Open,High,Low,Close,Volume,symbol,next_month_close,month_return,ema_3,...,rsi_3,rsi_7,rsi_14,macd_fast,macd_slow,atr_7,atr_14,obv_short,cmf_short,target_return
0,2015-06-01,38.167115,38.167115,35.449446,35.541573,58978100.0,A,37.819347,0.064088,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.897810e+07,NaN,0.064088
1,2015-07-01,35.916834,37.994820,35.658242,37.819347,54238300.0,A,33.534073,-0.113309,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.132164e+08,NaN,-0.113309
2,2015-08-01,37.791632,38.188758,31.003547,33.534073,56307300.0,A,31.705456,-0.054530,35.631664,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.690910e+07,NaN,-0.054530
3,2015-09-01,32.601296,34.162097,30.698787,31.705456,47113000.0,A,34.974453,0.103105,33.668560,...,17.767250,NaN,NaN,NaN,NaN,NaN,NaN,9.796100e+06,NaN,0.103105
4,2015-10-01,31.788222,35.289371,30.676745,34.974453,52993300.0,A,38.734951,0.107521,34.321507,...,55.802933,NaN,NaN,NaN,NaN,NaN,NaN,6.278940e+07,NaN,0.107521
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56445,2024-12-01,174.660798,180.692157,160.422036,161.892609,50091600.0,ZTS,169.811874,0.048917,169.852502,...,22.204406,39.955762,46.212128,-0.117985,1.874363,18.842723,19.624888,8.833711e+11,-0.193527,0.048917
56446,2025-01-01,163.820269,173.816214,159.567521,169.811874,53785800.0,ZTS,166.677551,-0.018458,169.832188,...,44.535074,46.677825,49.108515,-0.535629,1.357683,18.186433,19.240874,8.834249e+11,-0.103612,-0.018458
56447,2025-02-01,168.491422,176.803370,153.801005,166.677551,74287300.0,ZTS,164.096252,-0.015487,168.254870,...,38.050810,44.383483,48.006678,-1.109706,0.687372,18.874424,19.509552,8.833506e+11,-0.085533,-0.015487
56448,2025-03-01,165.690877,176.404724,157.767618,164.096252,52813200.0,ZTS,155.873993,-0.050106,166.175561,...,32.250165,42.381918,47.070013,-1.720532,-0.051549,18.840521,19.447235,8.832978e+11,-0.156213,-0.050106
56449,2025-04-01,163.368706,165.780565,139.230161,155.873993,63411400.0,ZTS,160.350006,0.028716,161.024777,...,18.659213,36.298633,44.117251,-2.887827,-1.285795,19.941933,19.954604,8.832344e+11,-0.151551,NaN

In [15]:
df = df.dropna()

In [16]:
df.isna().sum()

Date                0
Open                0
High                0
Low                 0
Close               0
Volume              0
symbol              0
next_month_close    0
month_return        0
ema_3               0
ema_6               0
ema_12              0
ema_24              0
rsi_3               0
rsi_7               0
rsi_14              0
macd_fast           0
macd_slow           0
atr_7               0
atr_14              0
obv_short           0
cmf_short           0
target_return       0
dtype: int64

In [17]:
df.to_csv("data/stocks_months_data.csv",
                  index=0)